name: Deploy to website
on:
  push:
    branches: ["master"]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@vv3.5.2

    - name: Setup Node.js environment
      uses: actions/setup-node@master

    - name: Setup pnpm and install dependcies
      uses: pnpm/action-setup@v2.2.4
      with:
       version: latest
       run_install: true

    - name: Run Tests
      run: pnpm test

    - name: Building the project
      run: pnpm build

    - name: 📂 Sync Dist Folder
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.FTP_SERVER}}
        username: ${{ secrets.FTP_ACCOUNT}}
        password: ${{ secrets.FTP_PASSWORD}}
        server-dir: "./vue-options-to-composition/"
        local-dir: "./dist/"
